# Generated by Django 3.1.7 on 2023-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0002_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='p_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
